### ISSUE TITLE
Redirect /oauth/authorize to login without logged in

### ISSUE THREAD

**Issue by otofune** [rinsuki/sea#1]
ログイン後に戻ってこれると嬉しい (?next= とかでパス渡せるといいのか？)

**Comment by rinsuki** [comment]
リダイレクトじゃなくて新規タブでログイン開いてログインし終わったら閉じて戻ってくるみたいな実装にしようと思っていた

**Comment by rinsuki** [comment]
`/login?after=close` 的な

**Comment by otofune** [comment]
それだと認可できないのでは、と思ったけど自発的にリロードし続ける JS とか入れとけばいいのか

**Comment by rinsuki** [comment]
認証したらリロード↓みたいなボタン置いとけばよさそう

**Comment by rinsuki** [comment]
@otofune ところで /oauth/authorize にログインしていない状態で行くと /login へのリンクが出るようになりましたがどうですか

**Comment by otofune** [comment]
よさそうですね
