### ISSUE TITLE
avatarFile の参照削除方法

### ISSUE THREAD

**Issue by motitaiyaki** [rinsuki/sea#40]
案

- `DELETE /api/v1/account/avatarFile` by otofune
- `PATCH /api/v1/account` with `{avatarFile: null}` by me
- `PATCH /api/v1/account` with `{avatarFile: 0}` by me
- `PATCH /api/v1/account` with `{avatarFile: -1}` by rinsuki

**Comment by rinsuki** [comment]
nullで上書きはundefinedとnullの区別が付けられない言語があるので避けたくて、まあ0かなあという気がする

**Comment by motitaiyaki** [comment]
それでよさそう
