### ISSUE TITLE
添付画像の削除

### ISSUE THREAD

**Issue by motitaiyaki** [rinsuki/sea#41]
の実装

**Comment by rinsuki** [comment]
参照削除とは

**Comment by motitaiyaki** [comment]
`album_files` に `deleted_at`? を置いて削除済みの挙動をさせたい（画像を間違えた時等）

**Comment by rinsuki** [comment]
#44 の実装後に恐らく `DELETE /api/v1/album/files/:id` みたいなAPIでファイルが消せるようになるはず

**Comment by motitaiyaki** [comment]
アルバム関連のエンドポイント未実装なの忘れてた
see #44
